### ISSUE TITLE
Unity3D support?

### ISSUE THREAD

**Issue by katopz** [ziyasal/FireSharp#28]
I try to `nuget` to Unity5 project via VS2015 v14 but it throw...

```
Severity	Code	Description	Project	File	Line
Error		Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Unity Subset v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

So it's not support Unity am I right? Or maybe some magic workaround to make it work?

Thanks

**Comment by Whyser** [comment]
As Unity doesn't support latest C#, things like `async` and `await` won't work, unless you are ONLY building for the Windows Store Platform, in which you can wrap all your code inside #if UNITY_METRO (or equivalent).

Since Firebase now have support (beta) for Unity (for Android and iOS), it would be nice for someone to wrap FireSharp as an temporary solution in their implementation. But it doesn't really belong on this GitHub repo. :)

**Comment by katopz** [comment]
Thanks
