### ISSUE TITLE
Request responded with status code=BadRequest, response={   "error" : "Could not parse auth token." } 

### ISSUE THREAD

**Issue by walaa118** [ziyasal/FireSharp#73]
when i try to use firebase notification : 

  IFirebaseConfig config = new FirebaseConfig
  {
     AuthSecret = "your_firebase_secret",
     BasePath = "https://yourfirebase.firebaseio.com/"
  };

what is the AuthSecret  ?!

is it any setting need in the application console.firebase?

**Comment by qqc** [comment]
The legacy AuthSecret method is hidden inside the Project Settings in the new Firebase Console under the label **Database Secrets.** In order to find out your AuthSecret, you'll need to navigate to Project Settings by pressing the cog icon in the sidebar, and then going to the Database tab. Either use the existing secret, or create a new one, and press the button to reveal it. Put this in your FirebaseConfig and everything should be good to go.

![capture](https://cloud.githubusercontent.com/assets/3880807/18967049/a41fd1b2-867b-11e6-81e9-e3a8a03b0a54.PNG)

**Comment by alberthoekstra** [comment]
Doesnt work for me, i cant find the database secrest in the Firebase console.
